name: Deploy Pages branch
on:
  push:
    branches:
      - master
  release:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        description: Version to publish docs for
jobs:
  deploy:
    name: Deploy Pages branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: actions/checkout@v3
      - run: chmod +x ./gradlew
      - name: Generate docs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: docgen
      - name: Build web book
        run: python ./doc/collate_data.py ./build/resources/main common/src/main/resources hexkinetics hexkineticsbook doc/template.html build/docgen/index.html build/docgen/book.json
      - name: Upload docgen folder
        uses: actions/upload-artifact@v3
        with:
          name: docgen
          path: build/docgen
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download docgen folder as latest
        uses: actions/download-artifact@v3
        with:
          name: docgen
          path: latest
      - name: Update latest version
        run: python _scripts/update_versions.py latest "${{ github.sha }}"
      - name: Add version from tag
        if: ${{ github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v') }}
        run: python _scripts/update_versions.py ref "${{ github.ref }}"
      - name: Add version from workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version != '' }}
        run: python _scripts/update_versions.py version "${{ github.event.inputs.version }}"
      - name: Commit changes
        run: |
          git config user.name "Documentation Generation Bot"
          git config user.email "noreply@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update docs from $GITHUB_REF"
          git push
